config/routes.rb
Rails.application.routes.draw do
  resources :tags, only: [:index, :new, :create, :show]
  devise_for :users, controller: { registrations: 'registrations' }
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
    get 'login',  to: 'devise/sessions#new'
  end
  get '/index', to: 'toppages#index'
  get '/about', to: 'toppages#about'
  root to: 'toppages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/regitration_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit( :name, :email, :password, :password_confirmation, :current_password)
  end

  def account_update_params
    params.require(:user).permit( :name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all.order('count DESC')
  end

  def new
    @word = Tag.new
  end

  def create
  end

  def show
  end

  private

  def tag_params
    params.require(:tag).permit(:word)
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  include TagsHelper # tag_count(word)
  def index
    if params[:keyword] && params[:number]
      @keyword = params[:keyword]
      @number = params[:number]
      tag_count(@keyword)
      find_videos(@keyword, @number)
    else # デフォルト
      @keyword = 'HIKAKIN'
      @number = 10
      find_videos(@keyword, @number)
      @word = Tag.first
    end
  end

  def about
  end
end

app/controllers/youtube.rb
require 'google/apis/youtube_v3'
require 'active_support/all'

def find_videos(keyword, number)
  service = Google::Apis::YoutubeV3::YouTubeService.new
  service.key = ENV["GOOGLE_YOUTUBE_API"]
  begin
    opt = {
      q: keyword,
      type: 'video',
      max_results: number,
      order: :viewCount,
    }
    @results = service.list_searches(:snippet, opt)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper

  def tag_links_partial_path
    if user_signed_in?
      'layouts/navigator/tag_elements/signed_in_links'
    else
      'layouts/navigator/tag_elements/non_signed_in_links'
    end
  end

end

app/helpers/tags_helper.rb
module TagsHelper
  def tag_count(word)
    if @word = Tag.find_by(word: word)
      @word.count += 1
      @word.save
    else
      @word = Tag.create(word: word)
    end
  end

  def find_videos(keyword, number)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = ENV["GOOGLE_YOUTUBE_API"]
    begin
      opt = {
        q: keyword,
        type: 'video',
        max_results: number,
        order: :viewCount,
      }
      @results = service.list_searches(:snippet, opt)
    end
  end

end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navigator.html.erb
<!-- layouts/_navigation_html.erb -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">
      <!-- 常に表示する要素 -->
      <div class="col-sm-7">
        <%= render 'layouts/navigator/header' %>
      </div><!-- col-sm-7 -->
      <!-- 小画面デバイスで隠す要素 -->
      <div class="col-sm-5">
        <%= render 'layouts/navigator/tag_elements' %>
      </div><!-- col-sm-5 -->
    </div><!-- row -->
  </div><!-- container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tagtube</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigator' %>
    <div class="container">
      <div class="col-md-10 col-md-offset-1">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/navigator/_header.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to 'Tagtube', root_path, class: 'navbar-brand' %>
</div>

app/views/layouts/navigator/_tag_elements.html.erb
<!-- layouts/navigation/_collapsible_elements.html.erb -->
<!-- ナビゲーションリンク/フォームなどのコンテンツをここにまとめて表示をオンオフできるようにする -->
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav ">
    <%= render tag_links_partial_path %>
  </ul>
</div><!-- navbar-collapse -->

app/views/layouts/navigator/tag_elements/_non_signed_in_links.html.erb
<li ><%= link_to 'Login', login_path %></li>
<li ><%= link_to 'Signup', signup_path %></li>

app/views/layouts/navigator/tag_elements/_signed_in_links.html.erb
<li class="dropdown pc-menu">
  <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
    <span id="user-name"><%= current_user.email %></span>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Tag Ranking', tags_path %></li>
    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
  </ul>
</li>
<li class="mobile-menu">
  <%= link_to 'Edit Profile', edit_user_registration_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
</li>

app/views/tags/index.html.erb
<h1>Tag Ranking</h1>
<% @tags.each do |tag| %>
  <p><%= tag.word %> : <%= tag.count %></p>
<% end %>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>
<h1>新規作成</h1>
<%= form_for @word, url: tags_path do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <%= f.label :word %></br>
  <%= f.text_field :word, class: 'form-control', placeholder: "半角スペースで複数検索可能" %>
  <%= f.submit "送信", class: 'btn btn-primary' %>
<% end %>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

app/views/toppages/_search_form.html.erb
<%= form_tag(index_path, method: :get, class: '') do %>
  <div class="form-group">
    <%= text_field_tag :keyword, params[:search], class: 'form-control', placeholder: "半角スペースで複数検索可能" %>
  </div>
  <div class="form-group">
    表示件数：
    <%= radio_button_tag :number, 10, { :checked => true } %> 10 </label>
    <%= radio_button_tag :number, 30 %> 30 </label>
    <%= radio_button_tag :number, 50 %> 50 </label>
    <label class="checkbox-inline">
  </div>
  <%= submit_tag '検索', class: 'btn btn-success' %>
<% end %><br>

app/views/toppages/_search_results.html.erb
<% i = 9 %>
<% @results.items.each do |item| %>
  <% hoge = item.id %>
  <% if i == 9 %>
    <iframe class="iframe-left" width="596" height="404" src="https://www.youtube.com/embed/<%= hoge.video_id %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    <% i = 1 %>
  <% else %>
    <iframe class="iframe-left" width="295" height="200" src="https://www.youtube.com/embed/<%= hoge.video_id %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    <% i += 1 %>
  <% end %>
<% end %>

app/views/toppages/about.html.erb
<h1>Toppages#about</h1>
<p>Find me in app/views/toppages/index.html.erb</p>

app/views/toppages/index.html.erb
<h1>タグを貼り付けて動画を検索</h1>
<p>ユーザー登録をするとタグの履歴を保存できます</p>
<div class="search_form">
  <%= render 'search_form' %>
</div>
<p><%= @keyword %>の検索結果</p><small>表示件数:<%= @number %>件 検索回数: <%= @word.count %></small>
<div class="search_results">
  <%= render 'search_results' %>
</div>